CHANGELOG.md
package.json
src/components/tmNotifications/README.md
src/components/tmNotifications/index.js
src/components/tmNotifications/tmNotification.vue
src/components/tmNotifications/tmNotifications.vue
src/index.js
tests/unit/__snapshots__/tmNotifications.spec.js.snap
tests/unit/tmNotifications.spec.js
tmNotifications.vue
yarn.lock

tmNotifications

---

CHANGELOG.md
package.json
src/components/TmBtn/TmBtn.vue
src/components/TmTextContainer/TmTextContainer.vue
src/components/TmTextContainer/index.js
src/components/TmTextMarkdown/TmTextMarkdown.vue
src/components/TmTextMarkdown/index.js
src/index.js
tests/unit/TmTextContainer.spec.js
tests/unit/TmTextMarkdown.spec.js
tests/unit/__snapshots__/TmCountdown.spec.js.snap
tests/unit/__snapshots__/TmTextContainer.spec.js.snap
tests/unit/__snapshots__/TmTextMarkdown.spec.js.snap
yarn.lock

For use in websites, also release 0.2.10

add tm-text-container

---

CHANGELOG.md
package.json
src/components/TmModalError/TmModalError.vue
tests/unit/__snapshots__/TmCountdown.spec.js.snap
tests/unit/__snapshots__/TmModalError.spec.js.snap

add fixes, bump version

---

CHANGELOG.md
package.json
src/components/TmLiStakeTransaction/TmLiStakeTransaction.vue
tests/unit/__snapshots__/TmBlock.spec.js.snap
tests/unit/__snapshots__/TmLiAnyTransaction.spec.js.snap
tests/unit/__snapshots__/TmLiStakeTransaction.spec.js.snap

didn't fix it enough before :/

fixed not using router on delegation tx

---

CHANGELOG.md
src/components/TmField/TmField.vue

sets TmField `options`' `:key="index"`

fedekunze/ Add key to TmField type select

---

CHANGELOG.md
src/components/TmLiAnyTransaction/TmLiAnyTransaction.vue
tests/unit/TmBlock.spec.js
tests/unit/TmLiAnyTransaction.spec.js
tests/unit/TmLiStakeTransaction.spec.js
tests/unit/__snapshots__/TmBlock.spec.js.snap
tests/unit/__snapshots__/TmLiStakeTransaction.spec.js.snap

`BeginRedelegate` tx was being shown as `Unknown Transaction Type`

fedekunze/fix BeginRedelegate tx

---

CHANGELOG.md
src/components/TmField/TmField.vue
tests/unit/TmField.spec.js

Don't trim text field values.

---

.circleci/config.yml

For this to work we'll have to add `NPM_TOKEN` env var in circleci project settings.

npm publish through circleci

---

package-lock.json
package.json
src/Modal/Modal.vue

`-webkit-overflow-scrolling: touch;`

Webkit scrolling

---

package-lock.json
package.json
src/CookieBanner/CookieBanner.vue

https://github.com/allinbits/design/issues/138

Add cookie functionality

---

package.json

Should be in `dependencies` not `devDependencies`.

tiny-cookie dependency

---

src/Modal/Modal.stories.js
src/Modal/Modal.vue

esc to close modal

---

src/Footer/Footer.stories.js
src/Footer/Footer.vue
src/Footer/data.js

Added popups in footer for social icons to close https://github.com/allinbits/design/issues/183. Since the docs theme will use this footer, I don't think I need to add them to the theme separately, we'll get popups as soon as we start using this footer instead of the local one, ok, @nassdonald ?
https://www.loom.com/share/2e11948da97f4c87b59f81ea8257fe4b
Went an extra mile to make transitions extra smooth 😄

Popups in footer

---

src/Modal/Modal.vue

Fixes the following error on modal close.
I wish there was a good way to test all this.

Modal bugfix and refactor

---

src/theme-cosmos.css

Closes https://github.com/allinbits/design/issues/141

Typography

---

.gitignore
now.json
package-lock.json
package.json
src/CodeBlock/CodeBlock.stories.js
src/CodeBlock/CodeBlock.vue
src/CookieBanner/CookieBanner.vue

Cookie Banner Styles

---

package-lock.json
package.json
src/index.js

Add missing GoZ exports

---

package.json
src/SeriesSignup/SeriesSignup.vue

Test: https://deploy-preview-193--cosmos-ui.netlify.app/iframe.html?id=seriessignup--normal&utm_event=scavenge&utm_source=twitter

Fetch UTM sources

---

src/Card/Card.vue
src/GozCard/GozCard.vue
src/GozRow/GozRow.vue
src/GozSection/GozSection.vue
src/Hero/GozHero.vue
src/NewsletterSignup/CosmosNewsletterSignup.vue
src/SeriesSignup/SeriesSignup.vue
src/Tooltip/Tooltip.vue
src/Tooltip/dict.json

Tooltip color fixes

---

package.json
src/NewsletterSignup/CosmosNewsletterSignup.vue
src/NewsletterSignup/NewsletterSignup.stories.js
src/SeriesSignup/SeriesSignup.vue

Related: https://github.com/allinbits/design/issues/296

MailerLite Migration

---

src/CodeBlock/CodeBlock.stories.js
src/CodeBlock/CodeBlock.vue
src/CodeBlock/data.js

closes https://github.com/cosmos/vuepress-theme-cosmos/issues/109

Solidity language support

---

package-lock.json
package.json
src/NewsletterSignup/NewsletterSignup.stories.js
src/NewsletterSignup/ValidatorNewsletterSignup.vue

- add input for validator name

Validator newsletter
